### ISSUE TITLE
Roadmap! Welcome pull request

### ISSUE THREAD

**Issue by anncwb** [vbenjs/vue-vben-admin#274]
Unconsciously, the project has basically stabilized. The project will continue to be maintained in the future. The development plan is as follows.

## English

- [x] Introduce windiCss to solve the problem of slow integration between tailwind.css and vite.
- [x]  Refactored login page to support multiple login methods
- [x] Homepage reconstruction, more beautiful
- [x] System management module (menu/permission/user) and development new branch 
- [x]  Dark theme
- [x] echarts 5.0
- [ ] The code is reconstructed in two ways: setup script and tsx SFC
- [ ] vuex code combing，Support vuex5, wait for vuex5 to be released
- [ ] Optimization and enhancement of various components
- [ ] New components
- [ ] The overall code is simplified and the code performance is optimized
- [ ] Complete documentation (including multiple languages)
- [ ] element-plus version
- [x] electron version
- [ ] The overall Typescript type is renewed

## 中文

- [x] 引入windiCss解决tailwind.css跟vite集成速度慢的问题.
- [x] 登录页重构,支持多种登录方式
- [x] 首页重构,更美观
- [x] 系统管理模块(菜单/权限/用户)及开发新分支 
- [x]  黑暗主题
- [x] echarts 5.0
- [ ] 代码使用setup script与 tsx SFC两种方式重构
- [ ]  vuex代码梳理，等待vuex5发布
- [ ] 各组件优化与加强
- [ ] 新的组件
- [ ] 整体代码简化,代码性能优化
- [ ] 文档完善(包含多语言)
- [ ] element-plus 版本
- [x] electron 版本
- [ ] 整体Typescript类型重新优化

**Comment by yuu2lee4** [comment]
后端不用node？

**Comment by anncwb** [comment]
> 后端nest走起

pr welcome

**Comment by vanthao03596** [comment]
working on laravel backend with jwt authentication.

**Comment by tomasky** [comment]
我写了一套nest后端，不太成熟，目前这个后台模板是见过除elementui和antdpro-v5,代码最优的了，但是感觉这个页面渲染加载还是太慢了,感觉很卡。

**Comment by anncwb** [comment]
> 我写了一套nest后端，不太成熟，目前这个后台模板是见过除elementui和antdpro-v5,代码结构最优的了，但是感觉这个页面渲染加载还是太慢了,感觉很卡。

nest是这个项目配套的吗？
卡顿如果是本地的话可能比较正常。有什么建议或者优化可以提给我或者pr给我。后面会优化下整体性能。

**Comment by tomasky** [comment]
nest是写的配合elementui的

**Comment by happy1836** [comment]
electron版本期待

**Comment by liyao2598330** [comment]
antdv Pro for vue3收费了，找了找发现这个最好了。打算用Python写一套后端，和这个搭配以后当template项目来用。😼

**Comment by cong99** [comment]
electron！

**Comment by zhengxinonly** [comment]
这个框架非常好用，很多js逻辑部分的封装配合 function api 使用起来非常方便。

在一开始看源码的时候，很多变量的定义都不明所以，等到看完所有的时候才发现是因为高度抽象了。根据传入的参数不同最终渲染出不同的页面，hooks 的封装虽然看起来吃力，但是用起来还是非常方便。

可能是之前只使用过 element-plus 的单组件使用原因。在看html层的封装，想改一个组件需要看另外一个组件的逻辑，然后还需要配合hooks组件的逻辑，以及各种参数调用，学习成本比较高。用 jsx 应该会比当前这种在多个文件中跳转阅读会好一些。

这个框架是我目前见过最好用的后台管理系统。优点是封装的非常好，使用起来非常方便，根据传递的参数可以渲染出不同的页面。缺点是封装的太狠了，不把整个框架的大部分源码都学习一遍，很难灵活使用框架自带的组件。

最后我看到框架中有部分组件使用 tsx 编写的，虽然逻辑目前看不懂，但是看起来比 SFC 舒服多了。期待组件早点重构为 tsx SFC 版本的组件

**Comment by lalawow** [comment]
@anncwb 你是想说vuex4吧？

**Comment by tuutoo** [comment]
Vite确实是快，现在用Vite的Admin管理模板没有几个，这是我目前看到的最好的一个(可以用高大全来形容)，而且还贴心的提供了thin版本的供开发用。赞👍🏻

**Comment by luliangce** [comment]
现在的代码是过不了package.json中的`type:check`的吧，这一点令我有一点困惑。

roadmap最后一条看起来不是很明确，这一条能解决类型检查的问题吗

**Comment by anncwb** [comment]
> 现在的代码是过不了package.json中的`type:check`的吧，这一点令我有一点困惑。
> 
> roadmap最后一条看起来不是很明确，这一条能解决类型检查的问题吗

是，因为`vue-tsc`是后面加的，现在其实也还不是很好用。等它稳定下来就可以进行类型问题修复

**Comment by snowchenlei** [comment]
登录保存jwt token如何实现

**Comment by Mikasa33** [comment]
> 登录保存jwt token如何实现

https://github.com/anncwb/vue-vben-admin/blob/655b74323653147943cbde2352208cb765c82b8a/src/store/modules/user.ts#L90

**Comment by snowchenlei** [comment]
`PermissionGuard`下的`whitePathList`应该提取到配置文件

**Comment by West121** [comment]
能封装个地图表单组建吗？填写位置带出地址和坐标

**Comment by iget** [comment]
能集成下pdf.js组件吗？ https://github.com/mozilla/pdf.js/

**Comment by levin950825** [comment]
能集成下 Bpmn 组件吗  提供工作流

**Comment by laizuan** [comment]
期待 elementui-plus 版本

**Comment by hyperq** [comment]
用vscode开发 代码补全很慢  不知道是啥原因

**Comment by adiramardiani** [comment]
Hi, @anncwb 

Btw, Thank you in  for this very beautiful template
There are some inputs from me :
- Without offending anyone, is it possible for all comments to be in English ?, frankly I sometimes have trouble reading comments in Chinese (no offense) :pray: 
- Still about the language, is it possible to use i18n on all labels, even if the label not have translation the default is set in English, sometimes there are still many labels that still use Chinese when the language setting is changed to English
- Those in Chinese label will be moved to translation(i18n) too

About language, I think it applies to other people ​​too, with that I hope this template can be used by more people. Once again, I don't mean to offend, if anyone objected, my statement doesn't need to be continued :pray: 

Regarding language and translation to English, I'm ready to help, but to be honest I'm still new to git, typescript, and the collaboration method

if allowed, I'm ready to be guided how the mechanism is

**Comment by colinin** [comment]
> Hi, @anncwb
> 
> Btw, Thank you in for this very beautiful template There are some inputs from me :
> 
> * Without offending anyone, is it possible for all comments to be in English ?, frankly I sometimes have trouble reading comments in Chinese (no offense) 🙏
> * Still about the language, is it possible to use i18n on all labels, even if the label not have translation the default is set in English, sometimes there are still many labels that still use Chinese when the language setting is changed to English
> * Those in Chinese label will be moved to translation(i18n) too
> 
> About language, I think it applies to other people ​​too, with that I hope this template can be used by more people. Once again, I don't mean to offend, if anyone objected, my statement doesn't need to be continued 🙏
> 
> Regarding language and translation to English, I'm ready to help, but to be honest I'm still new to git, typescript, and the collaboration method
> 
> if allowed, I'm ready to be guided how the mechanism is

Hello, maybe this will help you, but it's still in Chinese  : )

https://vvbin.cn/doc-next/dep/i18n.html#%E9%85%8D%E7%BD%AE%E9%BB%98%E8%AE%A4%E8%AF%AD%E8%A8%80

**Comment by adiramardiani** [comment]
Hi @colinin 

Thanks for recomend this pluginl, this is very handy but not in my context
I mean about @anncwb write above 
- [ ]  Complete documentation (including multiple languages) : 
I think what is meant here is [documentation](https://vvbin.cn/doc-next/), and what I add is in terms of code comments which should contain 2 languages ​​or only English (no offense). I also see that for translation, there are still many texts that do not use i18n (still hardcoded text), so when changing languages ​​in the language option, the language is still Chinese. 
I really want to help, but I need examples/procedures, because I'm not very good at programming

- [ ] ~vuex code combing，Support vuex5, wait for vuex5 to be released~ : Hi @anncwb refer this [vue 3 official document](https://vuejs.org/guide/scaling-up/state-management.html#what-is-state-management) 
I think this stage is no longer relevant and can be removed, we can continue using pinia because I read some official statement vuex5 is not exist, and vuex it self will no longer maintenance
![image](https://user-images.githubusercontent.com/8703419/159142268-ae115f79-e82d-41c0-b10a-f51b734dc7eb.png)

Thank you @anncwb and team

**Comment by lindongy** [comment]
首先感谢一下楼主们做了这个项目！
->   登录页重构,支持多种登录方式  
最近刚好做了oauth2多租户的案子，需要的话，可以提供基于keycloak-js的登录实现。

**Comment by MySecret** [comment]
期待element-plus版本！！！

**Comment by dennislan** [comment]
Any new version plan? such as 3.x roadmap, thks!

**Comment by adouzizi** [comment]
run起来的过程中需要输入sudo password，这个密码是什么呀各位大佬

**Comment by zhengbangbo** [comment]
> run起来的过程中需要输入sudo password，这个密码是什么呀各位大佬

@adouzizi 我也遇到了这个问题，请问你有找到原因吗？我第一次见，怀疑是有高权限的操作（感觉是制作自签名HTTPS证书相关的），可能得去代码中找了。

**Comment by adouzizi** [comment]
你好，不好意思，刚看到邮件，我还没有发现找到解决方案。



发自我的iPhone


------------------ Original ------------------
From: Zheng, Bang-Bo ***@***.***&gt;
Date: Thu,Feb 2,2023 10:27 AM
To: vbenjs/vue-vben-admin ***@***.***&gt;
Cc: adouliang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [vbenjs/vue-vben-admin] Roadmap! Welcome pull request (#274)





  
run起来的过程中需要输入sudo password，这个密码是什么呀各位大佬
  
@adouzizi 我也遇到了这个问题，请问你有找到原因吗？我第一次见，怀疑是有高权限的操作（感觉是制作自签名HTTPS证书相关的），可能得去代码中找了。

**Comment by anncwb** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days
